---
# tasks file for proxy

  - name: Install packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
       - nginx

  - name: Copy a new nginx.conf file into place
    copy:
      src: /rc-project/elk_playbook/roles/proxy/files/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Copy a new kibana.conf file into place
    copy:
      src: /rc-project/elk_playbook/roles/proxy/files/kibana.conf
      dest: /etc/nginx/conf.d/kibana.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Start Nginx
    systemd:
      name: nginx
      daemon_reload: yes
      state: started
      enabled: yes
